services:
  overleafmongo:
    image: "mongo:8.3"
    container_name: mongo
    hostname: mongo
    restart: always
    healthcheck:
      test: "mongosh --quiet --eval 'rs.hello().setName ? rs.hello().setName : rs.initiate({_id: \"overleaf\",members:[{_id: 0, host:\"mongo:27017\"}]})'"
      interval: 10s
      timeout: 10s
      retries: 5
    command: "--replSet overleaf"

    environment:
      GLIBC_TUNABLES: glibc.cpu.hwcaps=-SHSTK

    volumes:
      - ./data_db:/data/db
      - ./data_configdb:/data/configdb
      - ./backup:/backup
    networks:
      - overleaf-network
    expose: 
      - 27017

